name: 🧑‍　Auto Assign
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: wow-actions/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          CONFIG_FILE: .github/workflows/config/auto-assign.yml
