name: 🧑‍　Auto Assign
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: bubkoo/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
          CONFIG_FILE: .github/workflows/config/auto-assign.yml
