name: 🚫　Delete Stale Releases
# on:
#   repository_dispatch:
#     types: [released]
# jobs:
#   clean:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: wow-actions/use-app-token@v2
#         with:
#           app_id: ${{ secrets.APP_ID }}
#           private_key: ${{ secrets.PRIVATE_KEY }}
#
#       - uses: wow-actions/delete-stale-releases@v1
#         with:
#           GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
#           delete_tags: true
#           keep_latest_count: 3
#           group: '(?!^)@.*$'
#           exclude: |
#             @antv/x6@**
#             @antv/x6-common@**
#             @antv/x6-geometry@**
#             @antv/x6-plugin-**@**
#             @antv/x6-vue-shape@**
#             @antv/x6-react-shape@**
#             @antv/x6-angular-shape@**
#             @antv/x6-react-components@**

# delete all releases and tag
on:
  push:
    branches:
      - master
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: wow-actions/delete-stale-releases@v1
        with:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          delete_tags: true
          keep_latest_count: -1
