mode: chatops
branchName: short
branches:
  - label: bug
    prefix: fix/
  - label:
    - feature
    - enhancement
    prefix: feat/
  - label:
    - doc
    - document
    - documentation
    prefix: doc/
  - label: '*'
    prefix: issue/
  - label: question
    skip: true
experimental:
  branchNameArgument: true
commentMessage: |
  @${issue.user.login}

  Branch [${branchName}](${repository.html_url}/tree/${branchName}) was created for this issue. We will investigate into the matter and get back to you as soon as possible.

  感谢反馈问题或提供改进建议，我们创建了 [${branchName}](${repository.html_url}/tree/${branchName}) 分支来处理这个问题，你可以继续跟进后续的解决方案。
