# https://github.com/marketplace/actions/pr-labeler

pr(fix): ['fix/*', 'bug/*']
pr(chore): chore/*
pr(test): ['testing/*', 'test/*']
pr(feature): ['feature/*', 'feat/*']
pr(breaking): ['breaking/*', 'break/*']
pr(internal): ['internal/*', 'inter/*']
pr(documentation): ['documentation/*', 'document/*', 'doc/*']
pr(enhancement): ['enhancement/*', 'enhance/*']
pr(dependency): ['dependency/*', 'dep/*']
pr(refactor): ['refactoring/*', 'refactor/*']
