# @see https://help.semmle.com/lgtm-enterprise/user/help/lgtm.yml-configuration-file.html
# @template https://lgtm.com/static/downloads/lgtm.template.yml

queries:
  - exclude: js/use-before-declaration
  - exclude: js/polynomial-redos

extraction:
  javascript:
    index:
      filters:
        - exclude: "sites/x6-sites/static"
