language: node_js
node_js:
  - 12
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g yarn
  - npm install -g lerna
  - yarn bootstrap
script:
  - yarn build:dev
#   - yarn test
# after_script:
#   - yarn coveralls
