name: App token
description: Run a GitHub Action as a GitHub App instead of using secrets.GITHUB_TOKEN or a personal access token.
outputs:
  token:
    description: An installation token for the GitHub App on the current repository.
runs:
  using: node12
  main: ./index.js
branding:
  icon: unlock
  color: gray-dark
