name: '🐞 Bug Report'
description: Create a new issue. If your issue does not follow the guidelines, it may be closed automatically.
title: '🐞'
body:
  - type: markdown
    attributes:
      value: |
        ### Issue Feedback
        ⚠️ Before creating an issue, please make sure you have carefully read 👓 and searched 🔍 https://x6.antv.antgroup.com and https://x6.antv.antgroup.com/examples, and that you have already searched the relevant https://github.com/antvis/X6/issues?q=is%3Aissue and https://github.com/antvis/X6/discussions. Please only submit an issue when you believe there is no existing solution. ⚠️
        ### Package / Version Maintenance Policy
        All new features and enhancements are iterated on in the 3.x version; versions 1.x and 2.x mainly receive fixes for critical bugs.
  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: Clearly describe the problem you ran into. Please do not be stingy with words; provide as much useful information as you can.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Minimal reproduction link
      description: |
        1. Please provide a minimal reproducible example, and try to remove your business code as much as possible. This helps us reproduce and locate the issue faster; this is very important.
        2. It is recommended to use CodeSandbox (https://codesandbox.io/s/new) to reproduce your problem.
        3. The demos in the official examples (https://x6.antv.antgroup.com/examples) support editing code online. You can convert the code into a `codesandbox` and share the link with us. Please do not simply copy the official demo code to us without modification.
      placeholder: |
        Example: CodeSandbox URL
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please do not just paste a screenshot or a single sentence. We need detailed steps that we can follow to reproduce the issue.
      placeholder: |
        1. Open page...
        2. Click...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe the expected behavior. You know your code best, so please do not make us guess. For example: calling graph.centerContent() had no effect, but you expected the content to be centered after the call. If necessary, please use annotated screenshots to make the problem more obvious.
      placeholder: |
        I expected to see..., but I saw...
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: Platform
      value: |
        - OS: [macOS, Windows, Linux, React Native ...]
        - Browser: [Google Chrome, Safari, Firefox ...]
        - X6 Version: [3.1.0 ...]
    validations:
      required: true
  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or videos (optional but recommended)
      description: You can add screenshots or videos to help explain your problem.
      placeholder: |
        You can drag your image or video files here ↓
  - type: textarea
    id: additional
    attributes:
      label: Additional context (optional)
      description: For example, the business scenario or context where you ran into this bug.
