name: 💡 新功能
description: 给 X6 提出新的功能要求。
labels: ["template: story"]
body:
  - type: textarea
    id: describe_feature
    attributes:
      label: 功能描述
      description: 请尽可能详尽地说明这个功能的场景以及解决了什么问题。
    validations:
      required: true
  - type: textarea
    id: describe_solution
    attributes:
      label: 期望解决方案
      description: 描述你期望这个新功能的使用方式或者实现方式。
    validations:
      required: true
