import './vector/mixins'

import './container/mixins'
import './defs/mixins'
import './line/mixins'
import './path/mixins'
import './poly/mixins'
import './text/mixins'

export * from './vector/vector'

export * from './a/a'
export * from './circle/circle'
export * from './clippath/clippath'
export * from './defs/defs'
export * from './ellipse/ellipse'
export * from './foreignobject/foreignobject'
export * from './g/g'
export * from './gradient/linear'
export * from './gradient/radial'
export * from './image/image'
export * from './line/line'
export * from './marker/marker'
export * from './mask/mask'
export * from './path/path'
export * from './pattern/pattern'
export * from './polygon/polygon'
export * from './polyline/polyline'
export * from './rect/rect'
export * from './style/style'
export * from './svg/svg'
export * from './symbol/symbol'
export * from './text/text'
export * from './textpath/textpath'
export * from './tspan/tspan'
export * from './use/use'
