import './vector/mixins'

import './container/container-mixins'
import './fragment/mixins'
import './defs/mixins'
import './line/mixins'
import './path/mixins'
import './poly/mixins'
import './text/mixins'
import './filter/mixins'

export * from './fragment/fragment'
export * from './vector/vector'

export * from './a/a'
export * from './circle/circle'
export * from './clippath/clippath'
export * from './defs/defs'
export * from './desc/desc'
export * from './ellipse/ellipse'

export * from './fe-blend/fe-blend'
export * from './fe-color-matrix/fe-color-matrix'
export * from './fe-component-transfer/fe-component-transfer'
export * from './fe-composite/fe-composite'
export * from './fe-convolve-matrix/fe-convolve-matrix'
export * from './fe-diffuse-lighting/fe-diffuse-lighting'
export * from './fe-displacement-map/fe-displacement-map'
export * from './fe-flood/fe-flood'
export * from './fe-gaussian-blur/fe-gaussian-blur'
export * from './fe-image/fe-image'
export * from './fe-merge/fe-merge'
export * from './fe-morphology/fe-morphology'
export * from './fe-offset/fe-offset'
export * from './fe-specular-lighting/fe-specular-lighting'
export * from './fe-tile/fe-tile'
export * from './fe-turbulence/fe-turbulence'

export * from './foreignobject/foreignobject'
export * from './g/g'
export * from './gradient/linear'
export * from './gradient/radial'
export * from './image/image'
export * from './line/line'
export * from './marker/marker'
export * from './mask/mask'
export * from './path/path'
export * from './pattern/pattern'
export * from './polygon/polygon'
export * from './polyline/polyline'
export * from './rect/rect'
export * from './style/style'
export * from './svg/svg'
export * from './symbol/symbol'
export * from './title/title'
export * from './text/text'
export * from './textpath/textpath'
export * from './tspan/tspan'
export * from './use/use'
