# https://github.com/SvanBoxel/delete-merged-branch

name: Delete Merged Branch
on:
  pull_request:
    types: [closed]
jobs:
  deleting:
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/delete-merged-branch@v1.3.3
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"