export enum ShapeName {
  rectangle = 'rectangle',
  ellipse = 'ellipse',
  doubleEllipse = 'doubleEllipse',
  rhombus = 'rhombus',
  line = 'line',
  image = 'image',
  label = 'label',
  cylinder = 'cylinder',
  swimlane = 'swimlane',
  connector = 'connector',
  actor = 'actor',
  cloud = 'cloud',
  triangle = 'triangle',
  hexagon = 'hexagon',
  arrow = 'arrow',

  arrowConnector = 'arrowConnector',
  arrowClassic = 'classic',
  arrowClassicThin = 'classicThin',
  arrowBlock = 'block',
  arrowBlockThin = 'blockThin',
  arrowOpen = 'open',
  arrowOpenThin = 'openThin',
  arrowOval = 'oval',
  arrowDiamond = 'diamond',
  arrowDiamondThin = 'diamondThin',
}
