- name: bug
  color: ee0701
  description: Something isn't working.
- name: chore
  color: fef2c0
  description: Changes to the build process or auxiliary tools and libraries such as documentation generation.
- name: doc
  color: d4c5f9
  description: Improvements or additions to documentation.
- name: documentation
  color: d4c5f9
  description: Improvements or additions to documentation.
- name: duplicate
  color: fbca04
  description: This issue or pull request already exists.
- name: potential-duplicate
  color: fbca04
  description: This issue or pull request may duplicated with others.
- name: enhancement
  color: 5ebeff
  description: New feature or request.
- name: good first issue
  color: 7057ff
  description: Good for newcomers.
- name: help wanted
  color: 0e8a16
  description: An issue that could be handled by anyone, even new members of the community.
- name: invalid
  color: d73a4a
  description: This doesn't seem right.
- name: question
  color: d4c5f9
  description: Issues that are just questions.
- name: refactor
  color: fbca04
  description: A code change that neither fixes a bug nor adds a feature.
- name: stale
  color: eeeeee
  description: Issue that may be closed soon due to the original author not responding any more.
- name: style
  color: d4c5f9
  description: Changes that do not affect the meaning of the code.
- name: Need Reproduce
  color: fbca04
  description: Need reproduce infomations.
- name: needs-more-info
  color: fbca04
  description: PRs/Issues with either the default title or a blank body.
- name: no-issue-activity
  color: fbca04
  description:
- name: 'todo :spiral_notepad:'
  color: fbca04
  description:
- name: weekly-digest
  color: 7057ff
  description:
- name: WIP
  color: eeeeee
  description: The PR is a WIP.
- name: wontfix
  color: eeeeee
  description: The issue will not be fixed or otherwise handled. When applied, the issue should be closed.

# PR types
- name: PR(fix)
  color: ee0701
  description: ':bug: Bug Fix'
- name: PR(feature)
  color: 5ebeff
  description: ':tada: New feature'
- name: PR(enhancement)
  color: 5ebeff
  description: ':rocket: New feature or request'
- name: PR(chore)
  color: fef2c0
  description: ':turtle: Chore'
- name: PR(dependency)
  color: b4a8d1
  description: ':shamrock: Updates about dependencies'
- name: PR(documentation)
  color: d4c5f9
  description: ':book: Improvements or additions to documentation'
- name: PR(refactor)
  color: fbca04
  description: ':100: A code change that neither fixes a bug nor adds a feature'
- name: PR(test)
  color: e9f4dc
  description: ':white_check_mark: Adding missing tests'
- name: PR(internal)
  color: 2739db
  description: ':house: Internal'
- name: PR(breaking)
  color: fbca04
  description: ':boom: Breaking Change'

# PR status
- name: 'PR: draft'
  color: eeeeee
  description: PR is draft.
- name: 'PR: unreviewed'
  color: fbca04
  description: PR does not have any reviews.
- name: 'PR: reviewed-changes-requested'
  color: fbca04
  description: PR has reviewed and got Change request event.
- name: 'PR: partially-approved'
  color: c2e2a2
  description: PR has reviewd and got Approve from one of the reviewers.
- name: 'PR: reviewed-approved'
  color: 0e8a16
  description: PR has reviewed and got Approve from everyone.
- name: 'PR: merged'
  color: 662daf
  description: PR has merged.

# PR size
- name: size/XS
  color: 91ca55
  description: Denotes a PR that changes 0-9 lines, ignoring generated files.
- name: size/S
  color: c2e2a2
  description: Denotes a PR that changes 10-29 lines, ignoring generated files.
- name: size/M
  color: e9f4dc
  description: Denotes a PR that changes 30-99 lines, ignoring generated files.
- name: size/L
  color: fef6d7
  description: Denotes a PR that changes 100-499 lines, ignoring generated files.
- name: size/XL
  color: fef2c0
  description: Denotes a PR that changes 500-999 lines, ignoring generated files.
- name: size/XXL
  color: fbca04
  description: Denotes a PR that changes 1000+ lines, ignoring generated files.

# PR changed packages
- name: pkg:x6
  color: eeeeee
  description: Denotes a PR that changes packages/x6
- name: pkg:x6-react-shape
  color: eeeeee
  description: Denotes a PR that changes packages/x6-react-shape
- name: pkg:x6-react-components
  color: eeeeee
  description: Denotes a PR that changes packages/x6-react-components

# PR release status
- name: released
  color: 0e8a16
  description: PR has released
- name: released on @beta
  color: 0e8a16
  description: PR has released on @beta


