#!/bin/sh

lerna run build --stream --scope @antv/eslint-config
lerna run build --stream --scope @antv/stylelint-config

wait

lerna run build --stream --scope @antv/x6-common \
                         --scope @antv/x6-geometry \
                         --scope @antv/x6-react-components

wait

lerna run build --stream --scope @antv/x6

wait

lerna run build --stream --scope @antv/x6-vue-shape \
                         --scope @antv/x6-react-shape \
                         --scope @antv/x6-plugin-keyboard \
                         --scope @antv/x6-plugin-scroller \
                         --scope @antv/x6-plugin-selection \
                         --scope @antv/x6-plugin-snapline \
                         --scope @antv/x6-plugin-clipboard \
                         --scope @antv/x6-plugin-dnd \
                         --scope @antv/x6-plugin-stencil \
                         --scope @antv/x6-plugin-minimap \
                         --scope @antv/x6-plugin-transform \
                         --scope @antv/x6-plugin-history

wait
