#!/bin/sh

lerna run build --stream --scope @antv/eslint-config
lerna run build --stream --scope @antv/stylelint-config

wait

lerna run build --stream --scope @antv/x6-common \
                         --scope @antv/x6-geometry \
                         --scope @antv/x6-react-components

wait

lerna run build --stream --scope @antv/x6-next

wait

lerna run build --stream --scope @antv/x6-vue-shape \
                         --scope @antv/x6-react-shape \
                         --scope @antv/x6-plugin-keyboard \
                         --scope @antv/x6-plugin-scroller

wait
