#!/bin/sh

lerna run build --stream --scope @antv/eslint-config

wait

lerna run build --stream --scope @antv/x6-vector \
                         --scope @antv/x6-geometry \
                         --scope @antv/x6-react-components

wait

lerna run build --stream --scope @antv/x6

wait

lerna run build --stream --scope @antv/x6-vue-shape \
                         --scope @antv/x6-react-shape \
                         --scope @antv/x6-angular-shape \
                         --scope @antv/x6-sites-demos-helper

wait
