import { Shape } from '../shape/shape'

Shape.register('rectangle', Shape.Rectangle, true)
Shape.register('ellipse', Shape.Ellipse, true)
Shape.register('doubleEllipse', Shape.DoubleEllipse, true)
Shape.register('triangle', Shape.Triangle, true)
Shape.register('hexagon', Shape.Hexagon, true)
Shape.register('cylinder', Shape.Cylinder, true)
Shape.register('rhombus', Shape.Rhombus, true)
Shape.register('actor', Shape.Actor, true)
Shape.register('cloud', Shape.Cloud, true)
Shape.register('line', Shape.Line, true)
Shape.register('image', Shape.Image, true)
Shape.register('label', Shape.Label, true)
Shape.register('swimlane', Shape.Swimlane, true)
Shape.register('connector', Shape.Connector, true)
Shape.register('arrow', Shape.Arrow, true)
Shape.register('arrowConnector', Shape.ArrowConnector, true)
Shape.register('html', Shape.HTML, true)
