import { ShapeRegistry } from '../shape'

ShapeRegistry.register('rectangle', ShapeRegistry.Rectangle, true)
ShapeRegistry.register('ellipse', ShapeRegistry.Ellipse, true)
ShapeRegistry.register('doubleEllipse', ShapeRegistry.DoubleEllipse, true)
ShapeRegistry.register('triangle', ShapeRegistry.Triangle, true)
ShapeRegistry.register('hexagon', ShapeRegistry.Hexagon, true)
ShapeRegistry.register('cylinder', ShapeRegistry.Cylinder, true)
ShapeRegistry.register('rhombus', ShapeRegistry.Rhombus, true)
ShapeRegistry.register('actor', ShapeRegistry.Actor, true)
ShapeRegistry.register('cloud', ShapeRegistry.Cloud, true)
ShapeRegistry.register('line', ShapeRegistry.Line, true)
ShapeRegistry.register('image', ShapeRegistry.Image, true)
ShapeRegistry.register('label', ShapeRegistry.Label, true)
ShapeRegistry.register('swimlane', ShapeRegistry.Swimlane, true)
ShapeRegistry.register('connector', ShapeRegistry.Connector, true)
ShapeRegistry.register('arrow', ShapeRegistry.Arrow, true)
ShapeRegistry.register('arrowConnector', ShapeRegistry.ArrowConnector, true)
ShapeRegistry.register('html', ShapeRegistry.HTML, true)
