name: Delete Merged Branch
on: pull_request
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/delete-merged-branch@v1.3.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"