name: 👾　Label Commands
on:
  pull_request_target:
    types: [labeled, unlabeled]
  issues:
    types: [labeled, unlabeled]
jobs:
  cmd:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: wow-actions/label-commands@v1
        with:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          CONFIG_FILE: .github/workflows/config/label-commands.yml
