name: 👾　Label Commands
on:
  pull_request:
    types: [labeled, unlabeled]
  issues:
    types: [labeled, unlabeled]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: bubkoo/use-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: bubkoo/label-commands@v1
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          CONFIG_FILE: .github/workflows/config/label-commands.yml
