name: 🎗　Update Authors
on:
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta
jobs:
  authors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: wow-actions/update-authors@v1
        with:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN  }}
          bots: false
          path: CONTRIBUTORS
          commit: 'chore: update CONTRIBUTORS [skip ci]'
