name: 🔑　Update License
on:
  schedule:
    - cron: '0 3 1 1 *' # At 03:00 on day-of-month 1 in January.
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: wow-actions/use-app-token@v2
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - uses: FantasticFiasco/action-update-license-year@v2
      with:
        token: ${{ env.BOT_TOKEN }}
