name: 🚧　WIP

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      
jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: bubkoo/check-wip@v1
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
          labels: do-not-merge, wip, rfc
          keywords: WIP, RFC
          context: WIP
          wip_description: work in progress
          ready_description: ready for review
